details:
    page_title: AudioRobot
layout:
    - row_1_of_2:
        - col_1_of_4:
            - tile_template: just_value
              tile_id: rednoise
              title: ""
              classes:

        - col_1_of_4:
            - tile_template: just_value
              tile_id: redavg
              title: ""
              classes:

        - col_1_of_4:
            - tile_template: big_value
              tile_id: redbigvalue
              title: ""
              classes:
        - col_1_of_4:
            - tile_template: pie_chart
              tile_id: distancepiechart
              title: ""
              classes:

    - row_1_of_2:
        - col_1_of_4:
            - tile_template: just_value
              tile_id: bluenoise
              title: ""
              classes:

        - col_1_of_4:
            - tile_template: just_value
              tile_id: blueavg
              title: ""
              classes:

        - col_1_of_4:
            - tile_template: big_value
              tile_id: bluebigvalue
              title: ""
              classes:

        - col_1_of_4:
            - tile_template: pie_chart
              tile_id: maxspeedpiechart
              title: ""
              classes:
