details:
    page_title: AudioRobot
layout:
    - row_1_of_2:
        - col_1_of_4:
            - tile_template: just_value
              tile_id: noise
              title: "Noise Level"
              classes:

        - col_1_of_4:
            - tile_template: just_value
              tile_id: avg
              title: "Average Noise"
              classes:

        - col_1_of_4:
            - tile_template: big_value
              tile_id: bigvalue
              title: "WTF America"
              classes:
        - col_1_of_4:
            - tile_template: simple_percentage
              tile_id: simplepercentage
              title: "Speed"
              classes:

    - row_1_of_2:
        - col_1_of_4:
            - tile_template: norm_chart
              tile_id: normchart
              title: "Line chart for what idk"
              classes:

        - col_1_of_4:
            - tile_template: empty
              tile_id: empty
              title: Empty Tile
              classes:

        - col_1_of_4:
            - tile_template: empty
              tile_id: empty
              title: Empty Tile
              classes:

        - col_1_of_4:
            - tile_template: empty
              tile_id: empty
              title: Empty Tile
              classes:
